apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: "namespacequota-policy.example.com"
spec:
  failurePolicy: Fail
  paramKind:
    apiVersion: policy.example.com/v1
    kind: NamespaceQuota
  matchConstraints:
    resourceRules:
    - apiGroups:   ["apps"]
      apiVersions: ["v1"]
      operations:  ["CREATE", "UPDATE"]
      resources:   ["deployments"]
  validations:
    - expression: "object.spec.replicas <= params.spec.maxReplicas"
      reason: Invalid
---

apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: "namespacequota-binding-test.example.com"
spec:
  policyName: "namespacequota-policy.example.com"
  validationActions: [Deny]
  paramRef:
    name: "replica-quota"
    parameterNotFoundAction: Deny
