apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-deployment
  namespace: bootcamp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bootcamp-server
  template:
    metadata:
      labels:
        app: bootcamp-server
    spec:
      containers:
      - name: nexus-server
        image: server:v1.0
        ports:
        - containerPort: 8081