apiVersion: v1
kind: Service
metadata:
  name: nexus-service
  namespace: bootcamp
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
  selector:
    app: bootcamp-server