# strategic merge patch to change an environment variable
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  template:
    spec:
      containers:
        - name: nginx
          env:
            - name: apprentice
              value: Gibson