apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - helm-chart.yaml



namespace: gitea


patches:
  - target:
      kind: PersistentVolumeClaim
      name: gitea-shared-storage
    patch: |-
      - op: replace
        path: /spec/resources/requests/storage
        value: 3Gi
  - target:
      kind: Deployment
      name: gitea
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          limits:
            memory: 2Gi
  - target:
      kind: Pod
      name: gitea-test-connection
    patch: |-
      - op: replace
        path: /spec/restartPolicy
        value: OnFailure