apiVersion: v1
kind: PersistentVolume
metadata: 
    name: my-first-pv
    labels:
        type: local
spec: 
    storageClassName: hostpath
    accessModes: 
        - ReadWriteOnce
    capacity:
        storage: 1Gi
    hostPath: 
        path: /tmp/data
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: my-first-pvc
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      type: local